#!/bin/bash
#Used to generate commons-app/src/test/resources/db/schema.sql 
# for tests running on top of in memory storage H2 used to test Facades

script=`readlink -f $0`
basedir=`dirname $script`
sourcedir="${basedir}/../virtuoso/rdbms"
targetdir="${basedir}/../mysql/rdbms"

mkdir -p "$targetdir"

toreplace=(
'"DB"."ODCS".~'
'DB.ODCS.~'
'"~`'
'IDENTITY~AUTO_INCREMENT'
'LONG VARBINARY~BLOB'
'LONG VARCHAR~TEXT'
'LONG NVARCHAR~BLOB'
'DROP TABLE~DROP TABLE IF EXISTS'
)

# READ SCHEMA ##############################################
schema=$(<"${sourcedir}/schema.sql")

# CONVERT SCHEMA ###########################################

# remove sequences from schema (unsupported by MySQL)
schema=`echo "$schema" | grep -Ev "^sequence_set\\("`

# remove Virtuoso-only blocks
schema=`echo "$schema" | sed '/^-- BEGIN VIRTUOSO ONLY/,/^-- END VIRTUOSO ONLY/d'`

# remove comments that do not start at the beginning of a line
schema=`echo "$schema" | sed -r 's/\\s--\\s.*$//'`

# uncomment MySQL-only blocks '/^#/,/^\$/{/^#/!{/^\$/!d}}'
schema=`echo "$schema" | sed '/^--\\sBEGIN\\sMYSQL\\sONLY/,/^--\\sEND\\sMYSQL\\sONLY/{/^--\\sBEGIN/!{/^--\\sEND/!s/^--\\s//}}'`

# alter foreign key definitions
schema=`echo "$schema" | sed -r 's/^\\s*ADD\\sCONSTRAINT\\s.+FOREIGN\\sKEY/ADD FOREIGN KEY/'`

# translate SQL dialect from virtuoso to MySQL compatible
tmp="$IFS"
IFS=$'\n';
for x in ${toreplace[@]}; do
        IFS='~' read find replace <<< "$x"
	#echo "find${find}"
	#echo "replace${replace}"
	schema=${schema//$find/$replace}
done
IFS="$tmp"

# convert names to lowercase
schema=`echo "$schema" | sed -r 's/\`([A-Z_0-9]*)\`/\`\L\1\`/g'`

echo "-- THIS FILE IS AUTOMATICALLY GENERATED BY A SCRIPT." > "${targetdir}/schema.sql"
echo "-- DO NOT EDIT IT MANUALLY, YOUR CHANGES WILL BE LOST!!!" >> "${targetdir}/schema.sql"
echo -en "\n\n" >> "${targetdir}/schema.sql"
echo "$schema" >> "${targetdir}/schema.sql"

# READ DATA ################################################
data=$(<"${sourcedir}/data.sql")

# CONVERT SCHEMA ###########################################

# remove constraint checking clauses
data=`echo "$data" | sed -r 's/^fk_check_input_values\(([01])\);/SET FOREIGN_KEY_CHECKS = \1;/'`

# convert names to lowercase
data=`echo "$data" | sed -r 's/DB[.]ODCS[.]([A-Z_0-9]+)/\`\L\1\`/g'`

echo "-- THIS FILE IS AUTOMATICALLY GENERATED BY A SCRIPT." > "${targetdir}/data.sql"
echo "-- DO NOT EDIT IT MANUALLY, YOUR CHANGES WILL BE LOST!!!" >> "${targetdir}/data.sql"
echo -en "\n\n" >> "${targetdir}/data.sql"
echo "$data" >> "${targetdir}/data.sql"


