#!/bin/bash
#Used to generate commons-app/src/test/resources/db/schema.sql 
# for tests running on top of in memory storage H2 used to test Facades

script=`readlink -f $0`
basedir=`dirname $script`
sourcedir="${basedir}/../virtuoso/rdbms"
targetdir="${basedir}/../../commons-app/src/test/resources/db"

toreplace=(
'"DB"."ODCS".~'
'DB.ODCS.~'
'IDENTITY~AUTO_INCREMENT'
'"~`'
'LONG VARBINARY~BLOB'
'LONG VARCHAR~TEXT'
'LONG NVARCHAR~TEXT'
)

# read schema and data
schema=$(<"${sourcedir}/schema.sql")

# CONVERT SCHEMA ###########################################

# remove drop queries from schema
schema=`echo "$schema" | grep -Ev "^DROP\\s+TABLE\\s+"`

# remove comments that do not start at the beginning of a line
schema=`echo "$schema" | sed -r 's/\\s--\\s.*$//'`

# remove triggers (syntax seems to differ a lot)
schema=`echo "$schema" | sed '/^CREATE\\sTRIGGER/,/\};$/d'`

# translate SQL dialect from virtuoso to H2 compatible
tmp="$IFS"
IFS=$'\n';
for x in ${toreplace[@]}; do
        IFS='~' read find replace <<< "$x"
	#echo "find${find}"
	#echo "replace${replace}"
	schema=${schema//$find/$replace}
done
IFS="$tmp"

# translate CREATE SEQUENCE queries
schema=$(echo "$schema" | sed -r "s/sequence_set\\(\\s*'(.*)'\\s*,\\s*([0-9]+)\\s*,\\s*([0-9]+)\\s*\\);/CREATE SEQUENCE \`\\1\` START WITH \\2;/g")

echo "-- THIS FILE IS AUTOMATICALLY GENERATED BY A SCRIPT." > "${targetdir}/schema.sql"
echo "-- DO NOT EDIT IT MANUALLY, YOUR CHANGES WILL BE LOST!!!" >> "${targetdir}/schema.sql"
echo -en "\n\n" >> "${targetdir}/schema.sql"
echo "$schema" >> "${targetdir}/schema.sql"

