

ALTER TABLE dpu_instance NOCHECK CONSTRAINT all;
ALTER TABLE dpu_template NOCHECK CONSTRAINT all;
ALTER TABLE exec_context_dpu NOCHECK CONSTRAINT all;
ALTER TABLE exec_context_pipeline NOCHECK CONSTRAINT all;
ALTER TABLE exec_dataunit_info NOCHECK CONSTRAINT all;
ALTER TABLE exec_pipeline NOCHECK CONSTRAINT all;
ALTER TABLE exec_record NOCHECK CONSTRAINT all;
ALTER TABLE exec_schedule NOCHECK CONSTRAINT all;
ALTER TABLE exec_schedule_after NOCHECK CONSTRAINT all;
ALTER TABLE logging NOCHECK CONSTRAINT all;
ALTER TABLE ppl_edge NOCHECK CONSTRAINT all;
ALTER TABLE ppl_graph NOCHECK CONSTRAINT all;
ALTER TABLE ppl_model NOCHECK CONSTRAINT all;
ALTER TABLE ppl_node NOCHECK CONSTRAINT all;
ALTER TABLE ppl_open_event NOCHECK CONSTRAINT all;
ALTER TABLE ppl_position NOCHECK CONSTRAINT all;
ALTER TABLE ppl_ppl_conflicts NOCHECK CONSTRAINT all;
ALTER TABLE rdf_ns_prefix NOCHECK CONSTRAINT all;
ALTER TABLE sch_email NOCHECK CONSTRAINT all;
ALTER TABLE sch_sch_notification NOCHECK CONSTRAINT all;
ALTER TABLE sch_sch_notification_email NOCHECK CONSTRAINT all;
ALTER TABLE sch_usr_notification NOCHECK CONSTRAINT all;
ALTER TABLE sch_usr_notification_email NOCHECK CONSTRAINT all;
ALTER TABLE usr_user NOCHECK CONSTRAINT all;
ALTER TABLE usr_user_role NOCHECK CONSTRAINT all;

