package cz.cuni.mff.xrg.odcs.frontend.gui;

import java.util.HashMap;

import org.springframework.beans.factory.annotation.Autowired;

import com.vaadin.server.ExternalResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.BaseTheme;

import cz.cuni.mff.xrg.odcs.commons.app.auth.AuthenticationContext;
import cz.cuni.mff.xrg.odcs.frontend.RequestHolder;
import cz.cuni.mff.xrg.odcs.frontend.auth.AuthenticationService;
import cz.cuni.mff.xrg.odcs.frontend.gui.views.Login;
import cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigator;
import cz.cuni.mff.xrg.odcs.frontend.navigation.ClassNavigatorHolder;

/**
 * Class represent main application component. The component contains menu bar
 * and a place where to place application view.
 *
 * @author Petyr
 *
 */
public class MenuLayout extends CustomComponent {

	private static final long serialVersionUID = 1L;
	private ClassNavigator navigator;
	/**
	 * Authentication context used to render menu with respect to currently
	 * logged in user.
	 */
	@Autowired
	private AuthenticationContext authCtx;
	/**
	 * Authentication service handling logging in and out.
	 */
	@Autowired
	private AuthenticationService authService;
	/**
	 * Used layout.
	 */
	private VerticalLayout mainLayout;
	/**
	 * Menu bar.
	 */
	private HorizontalLayout menuBar;
	/**
	 * Layout for application views.
	 */
	private Panel viewLayout;
	Label userName;
	Button logOutButton;
	Embedded backendStatus;
	
	HashMap<String, Link> menuItems = new HashMap<>();

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public void enter() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	private VerticalLayout buildMainLayout() {
		// common part: create layout
		this.mainLayout = new VerticalLayout();
		this.mainLayout.setImmediate(false);
		this.mainLayout.setMargin(false);

		// top-level component properties
		this.setWidth("100.0%");

		// menuBar
		this.menuBar = new HorizontalLayout();
		this.menuBar.setImmediate(false);

		backendStatus = new Embedded();
		backendStatus.setWidth(16, Unit.PIXELS);
		backendStatus.setHeight(16, Unit.PIXELS);
		backendStatus.setStyleName("backendStatus");

		userName = new Label(authCtx.getUsername());
		userName.setWidth(100, Unit.PIXELS);
		userName.addStyleName("username");

		logOutButton = new Button();
		logOutButton.setWidth(16, Unit.PIXELS);
		logOutButton.setVisible(authCtx.isAuthenticated());
		logOutButton.setStyleName(BaseTheme.BUTTON_LINK);
		logOutButton.setIcon(new ThemeResource("icons/logout.png"), "Log out");
		logOutButton.addClickListener(new Button.ClickListener() {
			@Override
			public void buttonClick(Button.ClickEvent event) {
				authService.logout(RequestHolder.getRequest());
				authCtx.clear();
				refreshUserBar();
				navigator.navigateTo(Login.class);
			}
		});
		HorizontalLayout menuLine = new HorizontalLayout(menuBar, userName, logOutButton, backendStatus);
		menuLine.setSpacing(true);
		menuLine.setWidth(100, Unit.PERCENTAGE);
		menuLine.setHeight(45, Unit.PIXELS);
		menuLine.addStyleName("loginPanel");
		menuLine.setComponentAlignment(menuBar, Alignment.MIDDLE_LEFT);
		menuLine.setComponentAlignment(backendStatus, Alignment.MIDDLE_RIGHT);
		menuLine.setComponentAlignment(userName, Alignment.MIDDLE_RIGHT);
		menuLine.setComponentAlignment(logOutButton, Alignment.MIDDLE_RIGHT);
		menuLine.setExpandRatio(menuBar, 1.0f);
		this.mainLayout.addComponent(menuLine);

		// viewLayout
		this.viewLayout = new Panel();
		this.viewLayout.setStyleName("viewLayout");
		this.mainLayout.addComponent(viewLayout);

		refreshBackendStatus(false);

		return this.mainLayout;
	}

	/**
	 * Return layout for application views.
	 *
	 * @return layout for application views
	 */
	public Panel getViewLayout() {
		return this.viewLayout;
	}

	/**
	 * Refresh user bar.
	 */
	public void refreshUserBar() {
		userName.setValue(authCtx.getUsername());
		logOutButton.setVisible(authCtx.isAuthenticated());
	}

	/**
	 * Refreshes the status of backend. Green/red icon in header.
	 *
	 * @param isRunning
	 */
	public void refreshBackendStatus(boolean isRunning) {
		backendStatus.setDescription(isRunning ? "Backend is online!" : "Backend is offline!");
		backendStatus.setSource(new ThemeResource(isRunning ? "icons/online.png" : "icons/offline.png"));
	}

	/**
	 * Setup navigation and menu.
	 * 
	 * @param navigatorHolder 
	 */
	public void setNavigation(ClassNavigatorHolder navigatorHolder) {
		this.navigator = navigatorHolder;
		// init menuBar
		menuBar.setStyleName("v-menubar-new");
	
		Link main = new Link("ODCleanStore", new ExternalResource("#!"));
		main.addStyleName("v-menubar-menuitem-new");
		menuBar.addComponent(main);
		menuItems.put("", main);
		
		Link pipelines =  new Link("Pipelines", new ExternalResource("#!PipelineList"));
		pipelines.addStyleName("v-menubar-menuitem-new");
		menuBar.addComponent(pipelines);
		menuItems.put("PipelineList", pipelines);
		
		Link dpuTemplates = new Link("DPU Templates", new ExternalResource("#!DPURecord"));
		dpuTemplates.addStyleName("v-menubar-menuitem-new");
		menuBar.addComponent(dpuTemplates);
		menuItems.put("DPURecord", dpuTemplates);

		Link executionList = new Link("Execution Monitor", new ExternalResource("#!ExecutionList"));
		executionList.addStyleName("v-menubar-menuitem-new");
		menuBar.addComponent(executionList);
		menuItems.put("ExecutionList", executionList);
		
		Link scheduler = new Link("Scheduler", new ExternalResource("#!Scheduler"));
		scheduler.addStyleName("v-menubar-menuitem-new");
		menuBar.addComponent(scheduler);
		menuItems.put("Scheduler", scheduler);
		
		Link settings = new Link("Settings", new ExternalResource("#!Administrator"));
		settings.addStyleName("v-menubar-menuitem-new");
		menuBar.addComponent(settings);
		menuItems.put("Administrator", settings);

//		menuItems.put("", menuBar.addItem("Browse Data", new NavigateToCommand(ViewNames.DATA_BROWSER.getUrl()));
	}

	/**
	 * Sets active menu item. 
	 *
	 * @param viewName Item to set as active.
	 */
	public void setActiveMenuItem(String viewName) {
		for (Link item : menuItems.values()) {
			item.removeStyleName("v-menubar-menuitem-checked-new");
			item.addStyleName("v-menubar-menuitem-new");
		}
		Link activeMenu = menuItems.get(viewName);
		if (activeMenu != null) {
			activeMenu.addStyleName("v-menubar-menuitem-checked-new");;
		}
	}
}
