DROP TABLE "DB"."INTLIB"."DPU_INSTANCE";
DROP TABLE "DB"."INTLIB"."DPU_TEMPLATE";
DROP TABLE "DB"."INTLIB"."EXEC_DATAUNIT_INFO";
DROP TABLE "DB"."INTLIB"."EXEC_CONTEXT_PIPELINE";
DROP TABLE "DB"."INTLIB"."EXEC_CONTEXT_PROCCONTEXT";
DROP TABLE "DB"."INTLIB"."EXEC_CONTEXT_DPU";
DROP TABLE "DB"."INTLIB"."EXEC_RECORD";
DROP TABLE "DB"."INTLIB"."EXEC_PIPELINE";
DROP TABLE "DB"."INTLIB"."PPL_MODEL";
DROP TABLE "DB"."INTLIB"."PPL_EDGE";
DROP TABLE "DB"."INTLIB"."PPL_NODE";
DROP TABLE "DB"."INTLIB"."PPL_GRAPH";
DROP TABLE "DB"."INTLIB"."PPL_POSITION";

CREATE TABLE "DB"."INTLIB"."DPU_INSTANCE"
(
-- DPURecord
  "id" INTEGER IDENTITY,
  "name" VARCHAR(45),
  "description" VARCHAR(255),
  "type" SMALLINT,
  "jar_path" VARCHAR(255),
  "configuration" LONG VARBINARY,
-- DPUInstaceRecord
  "dpu_id" INTEGER,
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."DPU_TEMPLATE"
(
-- DPURecord
  "id" INTEGER IDENTITY,
  "name" VARCHAR(45),
  "description" VARCHAR(255),
  "type" SMALLINT,
  "jar_path" VARCHAR(255),
  "configuration" LONG VARBINARY,
-- DPUTemplateRecord
  "visibility" SMALLINT,
  "jar_description" VARCHAR(512),
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."EXEC_DATAUNIT_INFO"
(
  "id" INTEGER IDENTITY,
  "index" INTEGER,
  "directory" VARCHAR(255),
  "type" SMALLINT,
  "is_input" SMALLINT,
-- mapping for ExecutionContextImpl (exec_context_pipeline)
  "EXEC_CONTEXT_DPU_id" INTEGER, 
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."EXEC_CONTEXT_PIPELINE"
(
  "id" INTEGER IDENTITY,
  "directory" VARCHAR(255),
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."EXEC_CONTEXT_PROCCONTEXT"
(
  "EXEC_CONTEXT_PIPELINE_id" INTEGER,
  "EXEC_CONTEXT_DPU_id" INTEGER,
  dpu_execution INTEGER,
  PRIMARY KEY ( "EXEC_CONTEXT_PIPELINE_id", "dpu_execution")
);

CREATE TABLE "DB"."INTLIB"."EXEC_CONTEXT_DPU"
(
  "id" INTEGER IDENTITY,  
  "directory" VARCHAR(255),
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."EXEC_RECORD"
(
  "id" INTEGER IDENTITY,
  "r_time" DATETIME,
  "r_type" SMALLINT,
  "dpu_id" INTEGER,
  "execution_id" INTEGER,
  "short_message" LONG VARCHAR,
  "full_message" LONG VARCHAR,
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."EXEC_PIPELINE"
(
  "id" INTEGER IDENTITY,
  "status" INTEGER,
  "pipeline_id" INTEGER,
  "debug_mode" SMALLINT,
  "t_start" DATETIME,
  "t_end" DATETIME,
  "execution_directory" VARCHAR(255),
  "context_id" INTEGER,
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."PPL_MODEL"
(
  "id" INTEGER IDENTITY,
  "name" VARCHAR(45),
  "description" VARCHAR(255),
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."PPL_EDGE"
(
  "id" INTEGER IDENTITY,
  "graph_id" INTEGER,
  "node_from_id" INTEGER,
  "node_to_id" INTEGER,
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."PPL_NODE"
(
  "id" INTEGER IDENTITY,
  "graph_id" INTEGER,
  "instance_id" INTEGER,
  "position_id" INTEGER,
  PRIMARY KEY ("id")
);

CREATE TABLE "DB"."INTLIB"."PPL_GRAPH"
(
  "id" INTEGER IDENTITY,
  "pipeline_id" INTEGER,
  PRIMARY KEY ("id"),
  UNIQUE (pipeline_id)
);

CREATE TABLE "DB"."INTLIB"."PPL_POSITION"
(
  "id" INTEGER IDENTITY,
  "pos_x" INTEGER,
  "pos_y" INTEGER,
  PRIMARY KEY ("id")
);


-- CONSTRAINTS
