package cz.cuni.mff.xrg.odcs.frontend.gui.components;

import org.springframework.beans.factory.annotation.Autowired;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Validator;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Button.ClickEvent;

import cz.cuni.mff.xrg.odcs.commons.app.pipeline.DbPipeline;
import cz.cuni.mff.xrg.odcs.frontend.container.ReadOnlyContainer;
import cz.cuni.mff.xrg.odcs.frontend.container.accessor.PipelineNameAccessor;
import cz.cuni.mff.xrg.odcs.frontend.doa.container.InMemorySource;

/**
 * Dialog for pipeline conflict creation. Called from the {@link #PipelineEdit}.
 *
 * @author Maria Kukhar
 *
 */
public class PipelineConflicts extends Window {

	private static final long serialVersionUID = 1L;
	private VerticalLayout mainLayout;
	private Container container;
	@Autowired
	private DbPipeline dbPipeline;
	private TwinColSelect selectPipe;
	private Button clearConflicts;
	private boolean isInitialized = false;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public PipelineConflicts() {
		this.setResizable(false);
		this.setModal(true);
		this.setCaption("Pipeline Conflicts");
	}
	
	public void init() {
		buildMainLayout();
		this.setContent(mainLayout);
		setSizeUndefined();
		isInitialized = true;
	}
	
	public boolean isInitialized() {
		return isInitialized;
	}

	/**
	 * Builds main layout
	 *
	 * @return mainLayout VerticalLayout with all dialog components
	 */
	@AutoGenerated
	private VerticalLayout buildMainLayout() {

		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		mainLayout.setWidth("435px");

	
		container = new ReadOnlyContainer<>(
				new InMemorySource<>(new PipelineNameAccessor(), dbPipeline));

		//Component for pipelines select
		selectPipe = new TwinColSelect();
		selectPipe.setContainerDataSource(container);
		selectPipe.setNullSelectionAllowed(true);
		selectPipe.setMultiSelect(true);
		selectPipe.setImmediate(true);
		selectPipe.setWidth("400px");
		selectPipe.setHeight("200px");
		selectPipe.setItemCaptionPropertyId("name");
		selectPipe.setLeftColumnCaption("Pipeline list");
		selectPipe.setRightColumnCaption("Conflict pipelines");
		//selectPipe is mandatory component 
		selectPipe.addValidator(new Validator() {
			private static final long serialVersionUID = 1L;
			
			@Override
			public void validate(Object value) throws InvalidValueException {
				
				if (!value.toString().equals("[]")) {
					return;
				}
				throw new InvalidValueException(
						"Selected pipeline must be filled!");
				
			}
		});
		
		mainLayout.addComponent(selectPipe);
		
		clearConflicts = new Button("Clear Conflicts");
		clearConflicts.setImmediate(true);
		clearConflicts.addClickListener(new ClickListener() {

			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {

				selectPipe.setValue(null);
				
			}
		});
		mainLayout.addComponent(clearConflicts);
		mainLayout.setComponentAlignment(clearConflicts, Alignment.MIDDLE_RIGHT);
		
		//Layout with buttons Save and Cancel
		HorizontalLayout buttonBar = new HorizontalLayout();

		//Save button
		Button saveButton = new Button();
		saveButton.setCaption("OK");
		saveButton.setWidth("90px");
		saveButton.setImmediate(true);
		buttonBar.addComponent(saveButton);
		
		//Cancel button
		Button cancelButton = new Button("Cancel", new Button.ClickListener() {
			private static final long serialVersionUID = 1L;
			
			@Override
			public void buttonClick(Button.ClickEvent event) {
				close();
				
			}
		});
		cancelButton.setWidth("90px");
		cancelButton.setImmediate(true);
		buttonBar.addComponent(cancelButton);

		mainLayout.addComponent(buttonBar);

		return mainLayout;
	}


}
