package cz.cuni.mff.xrg.odcs.commons.app.data;

/**
 * Format scripts generated by {@link EdgeCompiler}.
 * 
 * @author Petyr
 */
public class EdgeFormater {
	
	/**
	 * Format the script string so it can be shown to user.
	 * 
	 * @param script
	 * @return 
	 */
	public String format(final String script) {		
		return script.replace(EdgeInstructions.Separator.getValue(), "\n");
	}
	
}
