package cz.cuni.mff.xrg.odcs.commons.app.data;

/**
 * Format scripts generated by {@link EdgeCompiler}.
 * 
 * @author Petyr
 */
public class EdgeFormater {

    /**
     * Format the script string so it can be shown to user.
     * 
     * @param script
     *            Script to format.
     * @return Formatted script.
     */
    public String format(final String script) {
        //final String removeRunAfter = script.replace(EdgeInstructions.RunAfter.getValue(), "");		
        return script.replace(EdgeInstructions.Separator.getValue(), "\n");
    }

}
