package cz.cuni.intlib.frontend.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.VerticalLayout;

import cz.cuni.intlib.frontend.gui.pages.*;

public class MainLayout extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private MenuBar menuBar;

	/**
	 * Class use as command to change sub-pages.
	 * @author Petyr
	 */
	private class ComponentChangeCommand implements Command {

		/**
		 * Parent page.
		 */
		private MainLayout parent;
		
		/**
		 * Component to show.
		 */
		private Class<?> component;
		
		/**
		 * @param parent
		 * @param component Component to show in reaction.
		 */
		public ComponentChangeCommand (MainLayout parent, Class<?> component) {
			this.parent = parent;
			this.component = component;
		}
		
		public void menuSelected(MenuItem selectedItem) {
			// replace component on position 1 (the page)
			CustomComponent component = null;

			try {
				component = (CustomComponent) this.component.newInstance();
			} catch (InstantiationException e) {
			} catch (IllegalAccessException e) {
			}
			
			this.parent.mainLayout.replaceComponent(this.parent.mainLayout.getComponent(1), component);
		}
		
	}
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		// init menuBar		
		menuBar.addItem("Pipelines", new ComponentChangeCommand(this, Pipelines.class));
		menuBar.addItem("DPUs", new ComponentChangeCommand(this, DPUs.class));
		menuBar.addItem("Execution Monitor", new ComponentChangeCommand(this, ExecutionMonitor.class));
		menuBar.addItem("Browse Data", new ComponentChangeCommand(this, DataBrowser.class));
		menuBar.addItem("Scheduler", new ComponentChangeCommand(this, Scheduler.class));
		menuBar.addItem("Administrator", new ComponentChangeCommand(this, Administrator.class));
		// menuBar.addItem("Help", new ComponentChangeCommand(this, null));
		
		// add default sub-page
		mainLayout.addComponent(new Initial());
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// menuBar
		menuBar = new MenuBar();
		menuBar.setImmediate(false);
		menuBar.setWidth("100.0%");
		menuBar.setHeight("20px");
		mainLayout.addComponent(menuBar);
		
		return mainLayout;
	}

}
