package cz.cuni.intlib.frontend.gui;

import com.vaadin.ui.AbstractLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

import cz.cuni.intlib.frontend.AppEntry;

public class MainLayout extends CustomComponent {

	/**
	 * Used layout.
	 */
	private VerticalLayout mainLayout;
	/**
	 * Menu bar.
	 */
	private MenuBar menuBar;
	/**
	 * Layout for application views.
	 */
	private VerticalLayout viewLayout;
	
	/**
	 * Class use as command to change sub-pages.
	 * @author Petyr
	 */
	private class NavigateToCommand implements Command {

		/**
		 * Url to navigate on.
		 */
		private String url;

		public NavigateToCommand (String url) {
			this.url = url;
		}
		
		public void menuSelected(MenuItem selectedItem) {
			// navigate to page -> navigator.navigateTo(MAINVIEW + "/" + menuitem);
			((AppEntry)UI.getCurrent()).getNavigator().navigateTo(this.url);
		}
		
	}
	
	public AbstractLayout getViewLayout() {
		return this.viewLayout;
	}
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		// init menuBar		
		menuBar.addItem("Pipelines", new NavigateToCommand(ViewNames.PipelineList.getUrl()) );
		menuBar.addItem("DPUs", new NavigateToCommand(ViewNames.DPU.getUrl()) );
		menuBar.addItem("Execution Monitor", new NavigateToCommand(ViewNames.ExecutionMonitor.getUrl()) );
		menuBar.addItem("Browse Data", new NavigateToCommand(ViewNames.DataBrowser.getUrl()) );
		menuBar.addItem("Scheduler", new NavigateToCommand(ViewNames.Scheduler.getUrl()) );
		menuBar.addItem("Administrator", new NavigateToCommand(ViewNames.Administrator.getUrl()) );		
	}
	
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		this.mainLayout = new VerticalLayout();
		this.mainLayout.setImmediate(false);
		this.mainLayout.setMargin(false);
		
		// top-level component properties
		this.setWidth("100.0%");
		this.setHeight("100.0%");
		
		// menuBar
		this.menuBar = new MenuBar();
		this.menuBar.setImmediate(false);
		this.menuBar.setWidth("100.0%");
		this.menuBar.setHeight("20px");
		this.mainLayout.addComponent(menuBar);
		// viewLayout
		this.viewLayout = new VerticalLayout();
		this.viewLayout.setWidth("100.0%");
		this.viewLayout.setHeight("100.0%");
		this.viewLayout.setMargin(false);
		this.mainLayout.addComponent(viewLayout);
		
		return this.mainLayout;
	}

}
